---
- name: create ext volume for data
  file: state=directory path={{ ext_grafana_data_volume }} owner=472 group=472

- name: create ext volume for conf
  file: state=directory path={{ ext_grafana_conf_volume }}

- name: put grafana.ini
  template: src=grafana.ini dest={{ ext_grafana_conf_volume }}/grafana.ini

- name: create provisioning folder
  file: state=directory path={{ ext_grafana_provisioning_volume }}

- name: create provisioning/datasources folder
  file: state=directory path={{ ext_grafana_provisioning_volume }}/datasources

- name: put datasource.yml
  template: src=datasource.yml dest={{ ext_grafana_provisioning_volume }}/datasources/datasource.yml
  when: grafana_auto_prometheus_config

- name: create provisioning/dashboards folder
  file: state=directory path={{ ext_grafana_provisioning_volume }}/dashboards

- name: put provider.yml
  template: src=provider.yml dest={{ ext_grafana_provisioning_volume }}/dashboards/provider.yml
  when: grafana_auto_dashboards_config

- name: create /root/dashboards
  file: state=directory path=/root/dashboards
  when: grafana_auto_dashboards_config

- name: checkout grafonnet
  git: repo=https://github.com/grafana/grafonnet-lib.git dest=/root/dashboards/grafonnet-lib
  when: grafana_auto_dashboards_config

- name: put dashboards
  template: src=dashboard.jsonnet dest=/root/dashboards/dashboard.jsonnet
  when: grafana_auto_dashboards_config

- name: create dashboards folder
  file: state=directory path={{ ext_grafana_dashboards_volume }}

- name: generate the dashboard
  shell: cd /root/dashboards && docker run --rm -i -v `pwd`:/src mexisme/jsonnet /jsonnet -J /src/grafonnet-lib /src/dashboard.jsonnet > {{ ext_grafana_dashboards_volume }}/dashboard.json
  when: grafana_auto_dashboards_config

- name: start a grafana container
  docker_container:
    image: grafana/grafana
    state: started
    read_only: yes
    recreate: yes
    restart_policy: always
    hostname: "{{ ansible_hostname }}-{{ grafana_container_name }}"
    ports:
      - "{{ grafana_port }}:3000"
    volumes:
      - "{{ ext_grafana_data_volume }}:/var/lib/grafana"
      - "{{ ext_grafana_conf_volume }}/grafana.ini:/etc/grafana/grafana.ini"
      - "{{ ext_grafana_provisioning_volume }}:/etc/grafana/provisioning"
      - "{{ ext_grafana_dashboards_volume }}:/var/lib/grafana/dashboards"
      - "{{ ext_grafana_tmp_volume }}:/var/tmp"
    name: "{{ grafana_container_name }}"
    restart_policy: always
  tags:
    - docker
