---
- name: create ext volume for data
  file: state=directory path={{ ext_grafana_data_volume }}

- name: start a grafana container
  docker:
    image: gitinsky/grafana:latest
    state: reloaded
    hostname: "{{ ansible_hostname }}-grafana"
    dns:
      - "{{ ansible_docker0.ipv4.address }}"
      - 8.8.8.8
    ports:
        - "{{ grafana_listen_address + ':' if grafana_listen_address is defined else '' }}3000:3000"
    volumes:
      - "{{ ext_grafana_data_volume }}:/usr/share/grafana/data"
      - "{{ ext_grafana_tmp_volume }}:/var/tmp"
    name: grafana
    restart_policy: always
  ignore_errors: yes
