---
- name: create ext volume for data
  file: state=directory path={{ ext_grafana_data_volume }} owner=472 group=472

- name: create ext volume for conf
  file: state=directory path={{ ext_grafana_conf_volume }}

- name: put grafana.ini
  template: src=grafana.ini dest={{ ext_grafana_conf_volume }}/grafana.ini

- name: create provisioning folder
  file: state=directory path={{ ext_grafana_provisioning_volume }}

- name: create provisioning/datasources folder
  file: state=directory path={{ ext_grafana_provisioning_volume }}/datasources

- name: put datasource.yml
  template: src=datasource.yml dest={{ ext_grafana_provisioning_volume }}/datasources/datasource.yml
  when: grafana_auto_prometheus_config

- name: create provisioning/dashboards folder
  file: state=directory path={{ ext_grafana_provisioning_volume }}/dashboards

- name: put provider.yml
  template: src=provider.yml dest={{ ext_grafana_provisioning_volume }}/dashboards/provider.yml
  when: grafana_auto_dashboards_config

- name: create /root/dashboards
  file: state=directory path=/root/dashboards
  when: grafana_auto_dashboards_config

- name: checkout grafonnet
  git: repo=https://github.com/grafana/grafonnet-lib.git dest=/root/dashboards/grafonnet-lib version=master
  when: grafana_auto_dashboards_config

- name: put grafonnet dashboards
  template: src=dashboard.jsonnet dest=/root/dashboards/{{ item.file_name }}.jsonnet
  when: grafana_auto_dashboards_config
  with_items: "{{ grafana_dashboards_grafonnet }}"

- name: create dashboards folder
  file: state=directory path={{ ext_grafana_dashboards_volume }}

- name: generate the dashboard
  shell: "cd /root/dashboards && docker run --rm -i -v `pwd`:/src mexisme/jsonnet /jsonnet -J /src/grafonnet-lib
           /src/{{ item.file_name }}.jsonnet > {{ ext_grafana_dashboards_volume }}/{{ item.file_name }}.json"
  when: grafana_auto_dashboards_config
  with_items: "{{ grafana_dashboards_grafonnet }}"

- name: put heatmaps
  template: src=heatmap.json dest={{ ext_grafana_dashboards_volume }}/{{ item.file_name }}.json
  when: grafana_auto_dashboards_config
  with_items: "{{ grafana_dashboards_heatmaps }}"

- name: start a grafana container
  docker_container:
    image: grafana/grafana
    state: started
    read_only: yes
    recreate: yes
    restart_policy: always
    hostname: "{{ ansible_hostname }}-{{ grafana_container_name }}"
    ports:
      - "{{ grafana_container_host_address }}:{{ grafana_port }}:3000"
    volumes:
      - "{{ ext_grafana_data_volume }}:/var/lib/grafana"
      - "{{ ext_grafana_conf_volume }}/grafana.ini:/etc/grafana/grafana.ini"
      - "{{ ext_grafana_provisioning_volume }}:/etc/grafana/provisioning"
      - "{{ ext_grafana_dashboards_volume }}:/var/lib/grafana/dashboards"
      - "{{ ext_grafana_tmp_volume }}:/var/tmp"
    name: "{{ grafana_container_name }}"
  tags:
    - docker

- uri:
    url: http://{{ grafana_container_host_address }}:{{ grafana_port }}/api/dashboards/db/{{ grafana_default_dashboard_slug }}
    return_content: yes
  register: dashboard
  retries: 10
  delay: 10
  when: "grafana_default_dashboard_slug is defined"

- uri:
    url: http://{{ grafana_container_host_address }}:{{ grafana_port }}/api/org/preferences
    method: PUT
    body_format: json
    body: '{"homeDashboardId": {{dashboard.json.dashboard.id}} }'
    user: "{{ grafana_admin_user }}"
    password: "{{ grafana_admin_password }}"
  when: "grafana_default_dashboard_slug is defined"
