---
- name: create ext volume for data
  file: state=directory path={{ ext_grafana_data_volume }}

- name: check if a grafana container is started
  command: bash -c "docker ps | grep grafana"
  ignore_errors: True
  register: result

- name: start a grafana container
  command: docker run -d
              -h {{ ansible_hostname }}-grafana
              --dns {{ ansible_docker0.ipv4.address }}
              --dns 8.8.8.8
              --read-only=true
              --restart=always
              -v {{ ext_grafana_data_volume }}:/usr/share/grafana/data
              -v {{ ext_grafana_tmp_volume }}:/var/tmp
              -p {{ grafana_port }}:3000
              --name=grafana gitinsky/grafana:0.1.0
  register: docker_id
  when: result|failed
